const LOADING_TODOS = "LOADING_TODOS";
const TODOS_DATA = "TODOS_DATA";
const ERROR_FETCHING_TODOS = "ERROR_FETCHING_TODOS";
const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";

export default {
    LOADING_TODOS,
    TODOS_DATA,
    ERROR_FETCHING_TODOS,
    ADD_TODO,
    DELETE_TODO,
}